name: Release
on:
  push:
    branches:
      - master
      - main

jobs:
  verify:
    name: Verify
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - name: Setup Node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: ".nvmrc"
      - name: Install
        run: |
          npm ci --omit=optional
          npm install --no-save warframe-worldstate-parser@^5.x warframe-worldstate-data@^3.x winston@^3
      - name: Build
        run: npm run build
      - name: Lint
        run: |
          npm run lint
          npx commitlint --last --verbose
      - name: Test Unit
        run: npm test
        env:
          CI: true
### TODO: Tests are currently disabled due to integration tests hanging
#      - name: Setup WireGuard
#        uses: niklaskeerl/easy-wireguard-action@v2
#        with:
#          WG_CONFIG_FILE: ${{ secrets.WG_CONFIG }}
#      - name: Test
#        run: npm run coverage
#        env:
#          CI: true
#          parallel: true
#      - name: Code Coverage
#        run: |
#          npm run report
#      - name: Coveralls
#        with:
#          github-token: ${{ secrets.GITHUB_TOKEN }}
#        uses: coverallsapp/github-action@master
  release:
    name: Release
    runs-on: ubuntu-latest
    needs:
      - verify
    permissions:
      id-token: write
      contents: write
      pull-requests: write
      issues: write
    steps:
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0
      - uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6.4.0
        with:
          node-version-file: ".nvmrc"
      - name: Install
        run: |
          npm ci --omit=optional
          npm install --no-save warframe-worldstate-parser@^5.x warframe-worldstate-data@^3.x winston@^3
      - name: Build
        run: npm run build
      - name: Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
